### ISSUE TITLE
error when i make the sdk

### ISSUE THREAD

**Issue by pppaulpeter** [daniel-falk/camera-analytics#4]
Hi Daniel,
when i exe the make command:make build-sdk
it complain the error in step 37 as shown in the following, do you know how to fix the problem? thanks!
Step 26/51 : RUN apt-get install libjpeg-dev -y
 ---> Using cache
 ---> d6171d05e2dc
Step 27/51 : WORKDIR /src
 ---> Using cache
 ---> b589f10c4d27
Step 28/51 : RUN git clone https://github.com/micropython/micropython.git
 ---> Using cache
 ---> 058d7dda279b
Step 29/51 : RUN cd micropython && git checkout v1.15
 ---> Using cache
 ---> e94621bc9403
Step 30/51 : WORKDIR /src/micropython/mpy-cross
 ---> Using cache
 ---> 7c1015c80cb9
Step 31/51 : RUN make
 ---> Using cache
 ---> f5127131dee1
Step 32/51 : WORKDIR /src/micropython/ports/unix
 ---> Using cache
 ---> 01c0078fdb48
Step 33/51 : RUN make submodules
 ---> Using cache
 ---> 34fa3462a1e4
Step 34/51 : COPY tools/ /tools
 ---> Using cache
 ---> 47aa0bf93bfc
Step 35/51 : COPY submodules/micropython-lib/micropython /tmp/micropython-lib
 ---> Using cache
 ---> 1a627fd98ae9
Step 36/51 : COPY submodules/micropython-lib/python-stdlib /tmp/micropython-lib
 ---> Using cache
 ---> b806afc55eab
Step 37/51 : RUN python3 /tools/install-libs.py /tmp/micropython-lib /usr/lib/micropython/
 ---> Running in 9401c17aacf7
python3: can't open file '/tools/install-libs.py': [Errno 2] No such file or directory
The command '/bin/sh -c python3 /tools/install-libs.py /tmp/micropython-lib /usr/lib/micropython/' returned a non-zero code: 2
Makefile:10: recipe for target 'build-sdk' failed
make: *** [build-sdk] Error 2

**Comment by daniel-falk** [comment]
Hi!

Seems like I had missed to check in one file. I do not have access to the original file right now, but I wrote a new one that seems to work. It's pushed to master now. I do however not have a camera with me now, so I have only verified on the host build of micropython.

Try to pull latest master and see if it works for you. If there are any more issues I can have another look.

This was the missing file: https://github.com/daniel-falk/camera-analytics/blob/master/tools/install-libs.py

**Comment by pppaulpeter** [comment]
> Hi!
> 
> Seems like I had missed to check in one file. I do not have access to the original file right now, but I wrote a new one that seems to work. It's pushed to master now. I do however not have a camera with me now, so I have only verified on the host build of micropython.
> 
> Try to pull latest master and see if it works for you. If there are any more issues I can have another look.
> 
> This was the missing file: https://github.com/daniel-falk/camera-analytics/blob/master/tools/install-libs.py

Hi Daniel,

the problem is solved, thanks a lot! And i also try it on axis camera, the python run perfactly!
by the way if i want to porting micropython to other embedded device not axis camera, will it be a good choice to reuse your docker file? how to repalce the cross-compile toolchain?

**Comment by daniel-falk** [comment]
Yes, you can reuse either the full dockerfile or only the first stage in it (`base`). Then it depends on how the cross-compile toolchain that you want to use is distributed, if it is distributed as a debian package you can create a new dockerfile which is based on the `base` image from the first build (`FROM camera-analytics:base`). If the toolchain is distributed as a docker image you can make a new mulitstage build which uses the toolchain image but copies the data from the `base` image. Something like this:

```diff
diff --git a/Dockerfile.my_target b/Dockerfile.my_target
new file mode 100644
index 0000000..84c3419
--- /dev/null
+++ b/Dockerfile.my_target
@@ -0,0 +1,16 @@
+# We need the base image that was build in the `make build-sdk-base` target,
+# we name that 'base':
+FROM camera-analytics:base as base
+
+# We use an official cross compilation SDK image as the
+# image to create the container we run our cross compilation in:
+FROM axisecp/acap-sdk:3.4.2-armv7hf-ubuntu20.04 as builder
+
+# Micropython source and libraries was already populated in the
+# base image, copy them to this SDK image:
+COPY --from=base /src /src
+COPY --from=base /usr/lib/micropython/ /usr/lib/micropython/
+
+# CC and CXX as well as PKG_CONFIG_PATH is set by the
+# SDK container in the ENTRYPOINT, we can just run the container
+# and the environment will be set up
diff --git a/Makefile b/Makefile
index ff8a505..a6d286a 100644
--- a/Makefile
+++ b/Makefile
@@ -6,6 +6,17 @@ IMAGE_TAG ?= latest
 build-sdk-base:
 	docker build . --target=base -t ${IMAGE_NAME}:base ${BUILD_OPTS}
 
+build-sdk-my-target: build-sdk-base
+	docker build . -f Dockerfile.my_target -t ${IMAGE_NAME}:my-target ${BUILD_OPTS}
+
+build-mpy-my-target: build-sdk-my-target
+	docker run --rm -v `pwd`/submodules:/submodules ${IMAGE_NAME}:my-target bash -c '\
+		cd /src/micropython/ports/unix && \
+		make deplibs && \
+		PKG_CONFIG_PATH=/src/micropython/ports/unix/build-standard/lib/libffi/ make && \
+		file micropython && \
+		cat micropython' >> micropython.my_target
+
 build-sdk:
 	docker build . -t ${IMAGE_NAME}:${IMAGE_TAG} ${BUILD_OPTS}
 ```

OBS, I have not tested the code above. My idea when using a multistage build with the `base` image first and then the `sdk` image was that it should be modular and reusable in a way like this. I.e. everything that should be shared between different kinds of builds should be done in the `base` image. Since I have not used the `base` image more then once, that might not be the case in reality. Feel free to reorganize the base image so that it works for both you and me and upload a pull-request on that.
